apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-db
  labels:
    app: db
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data
