apiVersion: v1
kind: Service
metadata:
  namespace: flask-app
  name: db
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
