---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secret
  namespace: flask-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDA6IO+ORGEQPS784hlN26ojRPVELag7/p7zNb14U5g3I9XY4h0y8hMpaySoPC2VEhjUVAntZ3vN8NqHPwObcIpJkkXpaD0fhXycUtroTZwivmll1q7c6AM6eQ53CLfgpWl0ggbbhsXCdR1bP6Nxzrv5ansTB1Ct1sXjsgcA9RtyMHCgyhqJiG33Mp07CZegM9S1iwmeNOoDSKrG/HMZeM4LS1/L1cIwNWLIEOro0jOd7tHIOwXEYT1NWj2eh/ofQReGDto5lRxWBJUSAe2ORE/BUIWa63GRJjbwfse5+5WzXwEDab3FAK9q14cfosiYgpBmysOGeKUqeswWDrGuJN/Z5Hh3KKZpuNjW/0X0pOdrD0sUm1Pe6j2wsWqQKpDL/fkqzLgnRrutabR39rYQClkwVPxpQPaltF+kwtkHPvGjQMZQe6eB3XDXfQ7Lng2vPboyFRrX7PrzlAGCt6h3vBpPakQv35D1TtqRFqpDBZPb2DIRhSsHd7PCabXYFI3B9B2HneFRZWtS+Oud5GO6R0tXgIfsufb4/7EJtHxMR5qmsTATYxAk4Xn1E91xXMAVYw+yoI71IgU2VoCrEqlReFv/h1oOwLfMdMtxCF6QmrAxHtDuSkQvbLc6TBAxm6YMW+qij0lXzQ9Y0pAA3dxK06tLBrkUE/bFdMylCxAacG4EF6eKOq1hTfrjP0jopEtBUJxJNBZ8xxkC3NQGPqaUnBmR/hBwuwrnXZ2v7qIAZsIMA==
    POSTGRES_USER: AgDKLOTo6MRjpPzn3/aaAuyu91xl1gKBhNBHMHN6lefT2kVg/paBL+TwQc5ZrKQXSX0LYT1QzDgZrEq/xl+MCVCtcXjeALP26GjFTB6u38YGv+Mu+9F+acoPkkvPh8Ev4YGIfzv+mSLOIjlmg9ENauOSYd7zf7whQ7jb1VLK3pom4mCyM/brlF76AEX5g4xNuFcTvPgaEF4FKR+AOtQjgHmtzY8Az6/ezd6a2oASZx/JcLQVQAz4LGVKL803Qty4sLrDkqEf2CXS65qyEp+2yz1wUP5aSXxM7FOvBN41T9xU6ZLrENfDqih34/FZz690jrd91tK139ORa7nRqGdPsZXN0qv95+Pobf4a1ivcFOtzNNoe1yHxyBz3GvsNne1LxpnJ84tGtmftJXZFGH+r5rszxfBolKHAacvwQriVECG71vdjPBsZ6bVvUHRXYwJcKWhynhnsGNzRbDnIixh+fDZ27DA6KaGu1Y0jjfzC3szTYHlHP6LzsQNstlAocDH22pXJsgOb+NbiuP6jFEj5SbZIQxL89fc/zdTap6XSvs/poE+AbUGApEzmrb6X5jwDW8oUQGkFJSL3V0d4RZC/x6M3jC27kAOXZnuVricm54MkaqQWdMomiHtWjy1N/ShWnbPyA6nfjBsH1dhp1ae2c1CygMFVtjCo3nQS1Sf8V9FCXAB7gLUJz5mW+To1ZDFYz+xf2YZNncw0c7k=
  template:
    metadata:
      name: postgres-db-secret
      namespace: flask-app
