apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  namespace: flask-app
spec:
  selector:
    matchLabels:
      app: db
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

