apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  namespace: flask-app
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

