apiVersion: v1
kind: ResourceQuota
metadata:
  name: flask-app-quota
  namespace: flask-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "2.5"
    limits.memory: "5Gi"
    pods: "6"
    persistentvolumeclaims: "2"
