---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secret
  namespace: flask-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAJq2pffrC67fqoAOO6jtpGjGiqrnKqiXjPD1z9tdZYICgPYUny95IifiP7AbkoiqXHEo/Buate7Ppymz+DBnjm4hNCMpYRHOIz3X96vrVg+KSXi+BJPt5HDywQDqPQ6YYUXxLLW2VVHMUGk7J40dvNqxFiyNpS0aCOOBLjYBimHM5EOosGXISYgb0Vgs2WitTjWRNtTBaDrCyb5EU71+r6RU022XQdxzGiv2OVpqMf5/HSVnezoJYwVcYCVppZqJi98g4Dfm2GG8RClFYeifQsAou6dI5nGDWr8WQ47mwlwTmX+2IaWR8BteRJMmQZCVKtrZ6SC+nqeiYf96zu9N3xk9pvtYSOqHmGGPVAUfDFOk385fR0zv0kfNkPSzwBUS+/fs3vmsM3eJECXByBfP6OuVBeliWu8WEc+Ml4Yt7ZBwyJjd3xZN8GbmICJv7kyaGa6TD2t6+bIcUqIwYw+iU3zAgyh8KqIjY5EvjpeEou+kcT35kJPxlzHtoTnZQceC+AB9FAn1VYVg/JcKpEUx1aPq2gcCCy6MsGi9dfYV0M+90DRi+AXpROwwgQYWRsfTgk7u8bbdrY8LQodRaITIUL5NcsnV9e44w6Y068ePJvSkq0dKRG05J80DmZ2seZhsv8qonAhDCXsknIXeYWBrFAmzJyDCK7vW8qyAbs2raYLZf1JZSYI/GzQCEIeFCuYRSlagsM0J2gyFKdpdL5/r8i5duUJ905KtLwXbnVO/DpfA==
    POSTGRES_USER: AgB5btvZ+zY2sOa/ypBEfE8tA8TGm/vU2zcKiy+gtKBG1kFG49F/HVotlm+r+8iHEJgWHtgxhzOjaD60Y2EG6TMOsi7ke6g8z9gW8QSg7kpGdS3FXcRhckvTYR2y7gITv1K3SezY+gr2GQsRY0nkK+5dEuJFZo8+fcs26IxNLuDebXU6SMVaO7U2cHE9w65e9fmMf5P7xUnH2z4KKdrYPUzw356O0p9JVWqrWtVZocry7Xsk1X4q2c3ebJju9PSn0S0TSb6NfTmbUjMNnOHauQnxSRmpO0F4kZD3nzIDCYYmf6v8251Ru9vdvbqUjWfD+/OktlNg/BByySROchtR+bys+fyYCMG5x+Kq/ODgCxSZtlAB3fQegSb0bZqsD/7JosZ0qTVFEhf0ZFeXMARkwlKciPtu8l4SNq4N1ebGoRjm66Cni7NtSUZgH6Zrj1A58LMWUZ0HHE1l30epapHcEH91tWgZu5iG0YgPNwZNQAdy1NHxqgrjaMAHgNhK78gADCF60wr3M0LyJfu2IYLJ+afwm0ViOM4+S0U9lT8LBYBT5ef0QNc/jdx3C/a7SBtalgG9F+1AHWUwYH0Va3OgqcW+6lfpehEHOk177UAt5K9AGz8rlhtfYtoI98j33PdpOE+TydxzbXiGNfafjscWsF8vlHAdfupv3tvysYmMgLGBEAb57P5DUbHWjhgj8ZS7+As5M+KFgMG8Zyw=
  template:
    metadata:
      name: postgres-db-secret
      namespace: flask-app
