---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secret
  namespace: flask-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBIpl4iS4vppx3iloYvEEqpzk9WWZw8i2n2NNU2SPuBiL+u39tIFUh09jJ1fUlixzoBJzzF/X6NlN7bNiUhQLqkiGXImP7YA+Ylh1ZGwwDAzxiSDYHVuGxGFBQnp2CFZadqVubkxx38yXwIinH32HHEHyd4t9Cs6tqeXFKEknT0fIljGLSn1h4P/vsoZMJTXGuEE7T6aRoyRWdFj4UPQ5QHufxNxpwjO2mWt9o1lXLvXbHSlHJo8OfMIY/wlXFG/EQRZZp0WOSFUlx9oqA8Np33L1a5HQ73xHsy4Uqmz7BW/gc8pu67uRfNmaUuvJo268aV2lYO1QpuKiyp8gmWQFWDxNTeb3KTcgWZUPtHVzXJb9AEfmfRuElWfUtMbPZy26YYK7mknhZKueLCzLW3R93y5lLu1MVcPec2fxceg3B/f6D6baoAeVivedXLPHzRhUx1n8WcqW9Fy7Zy8kL2w1etbQu31ulD8R2XFnNK8eP8JZQjJjhwdiWp9f0q7SRUUZBVH7h7KT149i6t3I1SSDiPH4G+kZIcOI7P7bAOW1rbpklgM+wysn3p5V/d4BVzzl8FPNCMWXnAQWJeC4rBcarjJw+mYfulKkvYdXstSDskTPqwplN4NYfI957lYr/IbsczcMmiH7ILuAzV9UMIufeRPZta7Y9p8hSYomx/fUKNqJPW1hKDkgz7n5ttmWpeNMS2wekJPtOCTVxl/RNUYfx3h8gLkb3M0yOQ2fJhCVcQ/Q==
    POSTGRES_USER: AgBkuWdFMtjI90UmI3DiF4NRAQxR90Dpz2Hvo+nnYvCqTLI8kJU0ih9TUDYEEak6zyP1djC1iE4FiJTTal4Ptz/i0Z40/pJMHO+vPE5WjP5IXN0h/dJBfVzmgV189Jgm/cBiKs6nuCNcueOl9lW4W5IhMBpPpLBQ5MLvkN+S1Jdr7FTZhzKPSpzKu1SC+s3Ct7RaaG7e2JcwlOHXlH9o6PoYRXtY7QiGmds7hfnKWYLY9TXrPu8NwgJ4ORiIG+JCJHdPJjdkRMNgJ6FU16vHF6Cfgvcr81AiQY6OZ0lRmqz4xtOTKPn9d45VWQUFokw7iOucwVX6+w7XWuZ1brxODXl0y9D4KOstLIFrCriklUqzdj75lJZ77SqGlMoHeOIH5gs7TL69fbJVAcxOe9uqLowazjN9iFFB7cEh+nzlinpQALJ+hFHTXf4Gp0N6g6gR9GBvF0Jauka6xlER9P1Wb3h/8rQRTP21kvf4HA03EiJn1g77lMbMDc7DjmRIrVNFcAU1l8P6z8NZTETNNMG5SH87UqP0BIR+TIdzIH+uPy6c3gJf8+J7vvhBpv+JKg78Jj2EGwW2O/Za9uC/bVLfWh1eN92N/G09OIDVT7Pp9Y5ELe4K+Vt67JrV3tH44VHWCiQ9YxFwfgP8bIUtXM+GFhIVCAk/MqQvxjRVja+fczYkq28BUQjCtzFlDlo5JdU6qaFldxMx8EpXhC0=
  template:
    metadata:
      name: postgres-db-secret
      namespace: flask-app
