---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secret
  namespace: flask-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBr4DbAX/VvAKVam2n9pHe55NqQ9jo3qQ/y6B52cVIZ+jNQZ/W8bjIDAuUSR3lc2inYRhysj5EVQpNIgqe3mOZh4pwvxoQh1Z+efJad2DvpBrjDIOZ1r+49/8BRmUjR645kBuALykdmF6EHCRdDkK/s2qnBtKVffnF5vX3VBOYV3FULLe5aLLoAUIkDJnF8zUTwtyl521BZcBEaiNcHpan/Xl2FOLISVZORS3np8uApwo8FqIoUgUe7z6v1ExzQbqJyqPtwEPkejj3zWOFYQXBcQCjrgf6jM8ZHZmrzBOtVA/wlkchfz7PYjUbj6fBOYCV4ljQzdjg9lcoGbrlKSjoQMY1/x1ktdndO86Djnm9i9NOJzvFCWvAZpCTjQxHUnRjk+1br49gd9JtkR/qn1E9kPwE6383XsYuJKkkwk3LHJBPtzPC+iv2o29uyDKdoTLlCKrqNKjX1PCid5UJbWGHnwdg8oQRZl1VnKwIcmUS9678B8kjH92Ojn/E0UKv66jfBaVHX0ATH0iQ2k/DmQBk/YLCxGmtKpHeL14iItsKPgERyqagFP/6SbdXmIvRRxdkFU66lWShyXBr1a07hmWNGdfg7/Van6iH7kP4mCh5cKxrl8teoxJ7otDbt4+TEf6mKsurYVG40Cj32EtmZ7sa3PbaMGqrNGLFDMTAk0MhD+JRFWP3Ld5uHp7S+1YKF0Y/zDJFvm6BngNXaaqSzwOsfnG8lAv3e8uWP6zz4sohuEg==
    POSTGRES_USER: AgClWEpssIc14qdkJFAjv0zeBqh+pUhdjPH1HkpVt96QOxdNh9h8IChtX/7aOCuNURFsrzuhEkLsJVDEeW5WGa4fluhoGBjMANETD68RET+pheoTf5KSnt+N+IqMzAPDWT0A/tPZiPayJIb2QFSqvQqZapKIm3Xt5PINWlrd+WHBDFYkIM9UCflNjRzaCLoNdEpAQkam0sDTKg9sj3UkJjey2RsxSzp2gnDZhHVGzSt8vzi5CCiwQ2kDCGY+LDfM8bcaM0WwKmTCwhNZzbCx15mFsF+sDnrFxkE/29SMEYbnd8s7FLELNVKhiNgfhWh4eJwfQONOX/2QZfYlDk1T5j3DRCejkNnjfeTn1oFk3y7XP1EbtizIg9QTEU83l9lUFwOKgNFTkzhLX1cNpuDzMYSUXb/W1OB4L1TbEu7HPZgDBt/EvsH+2nfxphiT3Ru6xGcg1NyRfr1kxn6L+aCqDyFdYGaF09RfEQkevoYXFpUzE4btLVBzt4z6b2BhXDFxAzjlvtlg9GSg5kWiWeY+EqoskcD21/9VNhZmidgEVnzsXNeAKqBEfuLwn71Hk4h8+UvyuQFJwcGQfc55rL23E2O6vYCvIiDxFlFVVMDAkPw+NdE84MQqEO2g2d5JJJd1BhdAHJSKACf4tkYmMwx+thhO8FLV8qiKD/qQuZKO41D9FZ8Wu/BEye3yL39JW+/WC8ctgsI4gUzassY=
  template:
    metadata:
      name: postgres-db-secret
      namespace: flask-app
